---
sudo: required

services:
  - docker

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/tmp/ansible:ro ansible/ansible:ubuntu1604py3 > "${container_id}"'
  - 'sudo docker exec -it "$(cat ${container_id})" pip3 install --upgrade pip ansible'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-galaxy install -v -r /tmp/ansible/ansible/requirements.yml'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -i /tmp/ansible/ansible/custom_ec2.py -b -e host=tag_Group_gitops_asg docker_host.yml'
  - 'sudo docker rm -f "$(cat ${container_id})"'
