---
sudo: required

services:
  - docker

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/tmp/ansible:ro ansible/ansible:ubuntu1604py3 > "${container_id}"'
  - 'sudo docker exec -it "$(cat ${container_id})" pip3 install --upgrade pip ansible docker pytest'
  - 'sudo docker exec "$(cat ${container_id})" ansible-galaxy install -v -r /tmp/ansible/ansible/requirements.yaml'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -i /tmp/ansible/ansible/custom_ec2.py -b -e host=localhost /tmp/ansible/ansible/docker_host.yaml'
  - 'sudo docker exec "$(cat ${container_id})" pip3 install -r /tmp/ansible/tests/requirements.txt'
  - 'sudo docker exec "$(cat ${container_id})" py.test -o cache_dir=/tmp /tmp/ansible/tests/docker_host.py'
  - 'sudo docker rm -f "$(cat ${container_id})"'
