packages_to_install:
- acct
- ansible
- arpwatch
- at
- atop
- autoconf
- automake
- bc
- blktrace
- build-essential
- byobu
- collectl
- conntrack
- cpp
- ctop
- curl
- dnsmasq
- dnsutils
- dstat
- fatrace
- ftp
- g++
- gawk
- gcc
- git
- glances
- htop
- httpry
- iftop
- inotify-tools
- iotop
- iperf
- iproute2
- iptables
- iptraf
- iputils-arping
- iputils-tracepath
- jq
- kernelshark
- linux-tools-common
- linux-tools-aws
- lsof
- ltrace
- lttng-tools
- msr-tools
- mtr
- net-tools
- netcat
- nethogs
- nicstat
- nload
- nmap
- nmon
- numactl
- perf-tools-unstable
- psmisc
- pv
- screen
- strace
- sysdig
- sysstat
- systemtap
- tcpdump
- tiptop
- tmux
- traceroute
- trace-cmd
- tree
- tshark
- ufw
- unzip
- vim
- wget
- wireshark-common
- xz-utils
- zip
